# Generated by Django 4.2.7 on 2023-11-16 08:07

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
