# Generated by Django 4.2.3 on 2023-11-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('tanks', 'Танки'), ('healers', 'Хилы'), ('damage dealers', 'ДД'), ('merchants', 'Торговцы'), ('guild masters', 'Гильдмастеры'), ('questgivers', 'Квестгиверы'), ('blacksmiths', 'Кузнецы'), ('leatherworkers', 'Кожевники'), ('potions makers', 'Зельевары'), ('spell masters', 'Мастера заклинаний')], default='tank', max_length=20),
        ),
    ]
